log_level: 10  # Logging parameters

# Camera parameters
device: /home/ivan/NextCloudEs/experiments_data/sources/lighting_pole_1/vid_3_cars_selected/car_night_merged_rawvideo_gray.mkv
resolution: [320, 240]
fps: 10
angle: -39
height: -3.325
cam_param_dir: ./camera_parameters/rpi

# clf_path: 'clf_models/detailed_separate_clf_dict.pcl'
clf_path: clf_models/lamp_pole_1.pcl  # Classifier path
out_dir: /tmp/car_night_merged_temp_3
saver: True  # Saving parameters

clahe_limit: 3  # Pre-processing parameters - CLAHE contrast adjustment for grayscale images only (COLOR = 0)
#bgs_method: {name: MOG2, parameters: [50, 16, True]}  # Background subtraction parameters, args given in OpenCV order
bgs_method: {name: CNT, parameters: [1]}
dilate_it: 1

time_window: 200 # Timers parameters
o_class_mapping: {0: noise, 1: pedestrian, 2: cyclist, 3: vehicle}
snd_recv_ports: [65433, 65434]  # Send and receive ports for interconnection with SmartLighting app
lamp_on_criteria: [2, 6]  # Format [q, N]: On how many q frames out of last N frames target objects have been detected

# Cascade filtering speeds up detection through filtering unlikely objects. Set value to zero to disable filtering.
cont_area_thr: 0.001  # Chosen 0.0005 Minimal object cnt area to be considered: object cnt area / RES[0] * RES[1] > cont_area_thr
extent_thr: 0.2
max_distance: 13 # Ignore objects which have distance more than MAX_DISTANCE: obj distance > MAX_DISTANCE.
margin: 0  # Ignore objects intersecting frame margin: left img border + MARGIN < obj coordinates < right img border - MARGIN